[
    {
        "name": "Baku",
        "adjective": ["Azerbaijani"],
        "cityStateType": "Cultured",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [128, 179, 255],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Food] from each Trade Route","[+2 Food] [in capital]"],
        "cities": ["Baku"]
    },
    {
        "name": "Chaco Canyon",
        "adjective": ["Chacoan"],
        "cityStateType": "Cultured",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [255, 217, 143],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Food] from each Trade Route","[+2 Food] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Chaco Canyon"]
    },
    {
        "name": "Djibouti",
        "adjective": ["Djiboutian"],
        "cityStateType": "Cultured",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [230, 166, 82],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Food] from each Trade Route","[+2 Food] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Djibouti"]
    },
    {
        "name": "Kuala Lumpur",
        "adjective": ["Kuala Lumpur"],
        "cityStateType": "Cultured",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [255, 255, 43],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Food] from each Trade Route","[+2 Food] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Kuala Lumpur"]
    },
    {
        "name": "Kuwait City",
        "adjective": ["Kuwati"],
        "cityStateType": "Cultured",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [230,230,230],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Food] from each Trade Route","[+2 Food] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Kuwait City"]
    },
    {
        "name": "Kyzyl",
        "adjective": ["Kyzyl"],
        "cityStateType": "Cultured",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [0, 163, 181],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Food] from each Trade Route","[+2 Food] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Kyzyl"]
    },
    {
        "name": "Ljubljana",
        "adjective": ["Slovenian"],
        "cityStateType": "Cultured",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [18,204,245],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Food] from each Trade Route","[+2 Food] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Ljubljana"]
    },
    {
        "name": "Luxembourg",
        "adjective": ["Luxembourg"],
        "cityStateType": "Cultured",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [54, 102, 255],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Food] from each Trade Route","[+2 Food] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Luxembourg"]
    },
    {
        "name": "Monaco",
        "adjective": ["Monaco"],
        "cityStateType": "Cultured",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [196, 87, 255],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Food] from each Trade Route","[+2 Food] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Monaco"]
    },
    {
        "name": "Montevideo",
        "adjective": ["Montevidean"],
        "cityStateType": "Cultured",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [125, 224, 0],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Food] from each Trade Route","[+2 Food] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Montevideo"]
    },
    {
        "name": "Nicosia",
        "adjective": ["Nicosia"],
        "cityStateType": "Cultured",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [172, 30, 185],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Food] from each Trade Route","[+2 Food] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Nicosia"]
    },
    {
        "name": "Reykjavik",
        "adjective": ["Reykjavik"],
        "cityStateType": "Cultured",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [128,255,128],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Food] from each Trade Route","[+2 Food] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Reykjavik"]
    },
    {
        "name": "Teheran",
        "adjective": ["Teheranian"],
        "cityStateType": "Cultured",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [172, 30, 185],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Food] from each Trade Route","[+2 Food] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Teheran"]
    },
    {
        "name": "Thimphu",
        "adjective": ["Thimphuan"],
        "cityStateType": "Cultured",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [54, 102, 255],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Food] from each Trade Route","[+2 Food] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Thimphu"]
    },
    {
        "name": "Ceygoa",
        "adjective": ["Ceygoan"],
        "cityStateType": "Cultured",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [54, 102, 255],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Food] from each Trade Route","[+2 Food] [in capital]"],
        "cities": ["Ceygoa"]
    },
    {
        "name": "Bangkok",
        "adjective": ["Bangkokian"],
        "cityStateType": "Maritime",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [179, 154, 255],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Gold] from each Trade Route","[+2 Gold] [in capital]"],
        "cities": ["Bangkok"]
    },
    {
        "name": "Cape Town",
        "adjective": ["Cape"],
        "cityStateType": "Maritime",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [230, 166, 82],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Gold] from each Trade Route","[+2 Gold] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Cape Town"]
    },
    {
        "name": "Islamabad",
        "adjective": ["Islamabadi"],
        "cityStateType": "Maritime",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [54,102,255],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Gold] from each Trade Route","[+2 Gold] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Islamabad"]
    },
    {
        "name": "Kampala",
        "adjective": ["Kampalan"],
        "cityStateType": "Maritime",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [172, 30, 185],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Gold] from each Trade Route","[+2 Gold] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Kampala"]
    },
    {
        "name": "Lima",
        "adjective": ["Liman"],
        "cityStateType": "Maritime",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [196, 87, 255],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Gold] from each Trade Route","[+2 Gold] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Lima"]
    },
    {
        "name": "Lusaka",
        "adjective": ["Lusakan"],
        "cityStateType": "Maritime",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [125, 224, 0],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Gold] from each Trade Route","[+2 Gold] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Lusaka"]
    },
    {
        "name": "Mogadishu",
        "adjective": ["Mogadishu"],
        "cityStateType": "Maritime",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [128, 179, 255],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Gold] from each Trade Route","[+2 Gold] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Mogadishu"]
    },
    {
        "name": "Ormus",
        "adjective": ["Ormus"],
        "cityStateType": "Maritime",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [179, 179, 179],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Gold] from each Trade Route","[+2 Gold] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Ormus"]
    },
    {
        "name": "Panama City",
        "adjective": ["Panamanian"],
        "cityStateType": "Maritime",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [255, 255, 128],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Gold] from each Trade Route","[+2 Gold] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Panama City"]
    },
    {
        "name": "Paramaribo",
        "adjective": ["Paramaribos"],
        "cityStateType": "Maritime",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [255, 217, 143],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Gold] from each Trade Route","[+2 Gold] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Paramaribo"]
    },
    {
        "name": "Phnom Penh",
        "adjective": ["Phnom Penher"],
        "cityStateType": "Maritime",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [25,75,235],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Gold] from each Trade Route","[+2 Gold] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Phnom Penh"]
    },
    {
        "name": "Port-au-Prince",
        "adjective": ["Haitian"],
        "cityStateType": "Maritime",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [128, 255, 128],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Gold] from each Trade Route","[+2 Gold] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Port-au-Prince"]
    },
    {
        "name": "Riga",
        "adjective": ["Rigan"],
        "cityStateType": "Maritime",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [18,204,245],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Gold] from each Trade Route","[+2 Gold] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Riga"]
    },
    {
        "name": "Santo Domingo",
        "adjective": ["Dominican"],
        "cityStateType": "Maritime",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [0,163,181],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Gold] from each Trade Route","[+2 Gold] [in capital]"],
        "cities": ["Santo Domingo"]
    },
    {
        "name": "Cahokia",
        "adjective": ["Cahokia"],
        "cityStateType": "Mercantile",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [230, 230, 230],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Production] from each Trade Route","[+2 Production] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Cahokia"]
    },
    {
        "name": "Colombo",
        "adjective": ["Colombo"],
        "cityStateType": "Mercantile",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [179, 154, 255],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Production] from each Trade Route","[+2 Production] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Colombo"]
    },
    {
        "name": "Dubai",
        "adjective": ["Emirati"],
        "cityStateType": "Mercantile",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [25, 75, 235],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Production] from each Trade Route","[+2 Production] [in capital]"],
        "cities": ["Dubai"]
    },
    {
        "name": "Gaborone",
        "adjective": ["Gaboronian"],
        "cityStateType": "Mercantile",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [255, 217, 143],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Production] from each Trade Route","[+2 Production] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Gaborone"]
    },
    {
        "name": "Hong Kong",
        "adjective": ["Hong Kong"],
        "cityStateType": "Mercantile",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [54, 102, 255],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Production] from each Trade Route","[+2 Production] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Hong Kong"]
    },
    {
        "name": "Lagos",
        "adjective": ["Lagosian"],
        "cityStateType": "Mercantile",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [128, 255, 128],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Production] from each Trade Route","[+2 Production] [in capital]"],
        "cities": ["Lagos"]
    },
    {
        "name": "Malacca",
        "adjective": ["Malacca"],
        "cityStateType": "Mercantile",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [18, 204, 245],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Production] from each Trade Route","[+2 Production] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Malacca"]
    },
    {
        "name": "Maseru",
        "adjective": ["Maseru"],
        "cityStateType": "Mercantile",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [128, 179, 255],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Production] from each Trade Route","[+2 Production] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Maseru"]
    },
    {
        "name": "Mohenjo-Daro",
        "adjective": ["Mohenjo"],
        "cityStateType": "Mercantile",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [125, 224, 0],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Production] from each Trade Route","[+2 Production] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Mohenjo-Daro"]
    },
    {
        "name": "Singapore",
        "adjective": ["Singaporean"],
        "cityStateType": "Mercantile",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [255, 255, 128],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Production] from each Trade Route","[+2 Production] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Singapore"]
    },
    {
        "name": "Tallinn",
        "adjective": ["Tallinner"],
        "cityStateType": "Mercantile",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [0, 163, 181],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Production] from each Trade Route","[+2 Production] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Tallinn"]
    },
    {
        "name": "Trieste",
        "adjective": ["Triestian"],
        "cityStateType": "Mercantile",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [230, 166, 82],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Production] from each Trade Route","[+2 Production] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Trieste"]
    },
    {
        "name": "Vaduz",
        "adjective": ["Liechtensteiner"],
        "cityStateType": "Mercantile",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [196, 87, 255],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Production] from each Trade Route","[+2 Production] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Vaduz"]
    },
    {
        "name": "Zurich",
        "adjective": ["Zurich"],
        "cityStateType": "Mercantile",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [179, 179, 179],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Production] from each Trade Route","[+2 Production] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Zurich"]
    },
    {
        "name": "Andorra",
        "adjective": ["Andorran"],
        "cityStateType": "Militaristic",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [230, 166, 82],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Science] from each Trade Route","[+2 Science] [in capital]"],
        "cities": ["Andorra"]
    },
    {
        "name": "Colchis",
        "adjective": ["Colchis"],
        "cityStateType": "Militaristic",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [172, 30, 185],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Science] from each Trade Route","[+2 Science] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Colchis"]
    },
    {
        "name": "Cyrene",
        "adjective": ["Cyreni"],
        "cityStateType": "Militaristic",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [18, 204, 245],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Science] from each Trade Route","[+2 Science] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Cyrene"]
    },
    {
        "name": "Harappa",
        "adjective": ["Harappan"],
        "cityStateType": "Militaristic",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [179, 154, 255],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Science] from each Trade Route","[+2 Science] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Harappa"]
    },
    {
        "name": "Havana",
        "adjective": ["Habanero"],
        "cityStateType": "Militaristic",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [128, 255, 128],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Science] from each Trade Route","[+2 Science] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Havana"]
    },
    {
        "name": "Tirana",
        "adjective": ["Tirana"],
        "cityStateType": "Militaristic",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [125, 224, 0],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Science] from each Trade Route","[+2 Science] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Tirana"]
    },
    {
        "name": "Troy",
        "adjective": ["Trojan"],
        "cityStateType": "Militaristic",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [179, 179, 179],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Science] from each Trade Route","[+2 Science] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Troy"]
    },
    {
        "name": "Valletta",
        "adjective": ["Valletta"],
        "cityStateType": "Militaristic",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [255, 255, 43],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Science] from each Trade Route","[+2 Science] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Valletta"]
    },
    {
        "name": "Bozrah",
        "adjective": ["Edomite"],
        "cityStateType": "Militaristic",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [255, 255, 43],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Science] from each Trade Route","[+2 Science] [in capital]"],
        "cities": ["Bozrah"]
    },
    {
        "name": "Damascus",
        "adjective": ["Syrian"],
        "cityStateType": "Militaristic",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [255, 255, 43],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Science] from each Trade Route","[+2 Science] [in capital]"],
        "cities": ["Damascus"]
    },
	{
		"name": "Dublin",
		"adjective": ["Dubliner"],
		"cityStateType": "Militaristic",

		"declaringWar": "War lingers in our hearts. Why carry on with a false peace?",
		"attacked": "You gormless radger! You'll dine on your own teeth before you set foot in Ireland!",
		"defeated": "A lonely wind blows through the highlands today. A dirge for Ireland. Can you hear it?",
		"outerColor": [0, 0, 0],
		"innerColor": [211,180,113],
		"cities": ["Dublin"],
		"uniques": ["Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"]
	},
	{
		"name": "Edinburgh",
		"adjective": ["Edinburghensian"],
		"cityStateType": "Militaristic",

		"declaringWar": "You shall stain this land no longer with your vileness! To arms, my countrymen - we ride to war!",
		"attacked": "Traitorous man! The Celtic peoples will not stand for such wanton abuse and slander - I shall have your head!",
		"defeated": "Vile ruler, know that you 'won' this war in name only!",
		"outerColor": [0, 0, 0],
		"innerColor": [0,102,102],
		"cities": ["Edinburgh"],
		"uniques": ["Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"]
	},
    {
        "name": "Geneva",
        "adjective": ["Geneva"],
        "cityStateType": "Religious",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [25, 75, 235],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Happiness] from each Trade Route","[+2 Happiness] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Geneva"]
    },
    {
        "name": "Ife",
        "adjective": ["Ife"],
        "cityStateType": "Religious",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [179, 179, 179],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Happiness] from each Trade Route","[+2 Happiness] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Ife"]
    },
    {
        "name": "Kathmandu",
        "adjective": ["Kathmandu"],
        "cityStateType": "Religious",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [196, 87, 255],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Happiness] from each Trade Route","[+2 Happiness] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Kathmandu"]
    },
    {
        "name": "La Venta",
        "adjective": ["La Venta"],
        "cityStateType": "Religious",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [18, 204, 245],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Happiness] from each Trade Route","[+2 Happiness] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["La Venta"]
    },
    {
        "name": "Qufu",
        "adjective": ["Qufu"],
        "cityStateType": "Religious",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [255, 255, 128],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Happiness] from each Trade Route","[+2 Happiness] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Qufu"]
    },
    {
        "name": "Sarajevo",
        "adjective": ["Sarajlija"],
        "cityStateType": "Religious",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [128, 255, 128],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Happiness] from each Trade Route","[+2 Happiness] [in capital]",
		"Will not be displayed in Civilopedia", "Will not be chosen for new games", "Excluded from map editor"],
        "cities": ["Sarajevo"]
    },
    {
        "name": "Taipei",
        "adjective": ["Taipei"],
        "cityStateType": "Religious",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [230, 230, 230],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Happiness] from each Trade Route","[+2 Happiness] [in capital]"],
        "cities": ["Taipei"]
    },
    {
        "name": "Wittenberg",
        "adjective": ["Wittenberg"],
        "cityStateType": "Religious",
        "declaringWar": "We have wanted this for a LONG time. War it shall be.",
        "attacked": "Very well, we will kick you back to the ancient era!",
        "defeated": "This isn't how it is supposed to be!",
        "outerColor": [0, 0, 0],
        "innerColor": [179, 154, 255],
        "uniques": [
		"[+4 Happiness] from each Trade Route","[+2 Happiness] [in capital]"],
        "cities": ["Wittenberg"]
    },
	{
		"name": "Ferrix",
		"adjective": ["Ferrix"],
		"cityStateType": "Productive",
		
		"declaringWar": "The Empire is a disease that thrives in darkness, it is never more alive than when we asleep. It’s easy for the dead to tell you to fight, and maybe it’s true, maybe fighting is useless. Perhaps it’s too late. But I’ll tell you this, if I could do it again, I’d wake up early and be fighting those bastards from the start! Fight the Empire!",
		"attacked": "But we were sleeping. I’ve been sleeping. And I’ve been turning away from the truth I wanted not to face. There is a wound that won’t heal at the center of the galaxy. There is a darkness reaching like rust into everything around us. We let it grow, and now it’s here. It’s here and it’s not visiting anymore. It wants to stay.",
		"defeated": "Stone and Sky.",
		"outerColor": [0, 0, 0],
		"innerColor": [204, 102, 0],
        "uniques": ["\"Borrows\" city names from other civilizations in the game",
		"[+4 Culture] from each Trade Route","[+2 Culture] [in capital]"],
		"cities": ["Ferrix"]
	},
]
